### ISSUE TITLE
Question about fALFF.m

### ISSUE THREAD

**Issue by Enigma-C137** [abhogal-lab/seeVR#12]
Hi @abhogal-lab 
I'm a beginner in neuroscience, and I have a few questions about the function fALFF.m.

Q1: I've noticed that function fALFF.m has been changed from
        %reference signal
        psdx = abs(xdft)/N; 
To
        psdx = (abs(xdft)/N).*2;

and The voxel-wise part of function still using

        psdx = (abs(xdft)/N).^2;
instead of

        psdx = ((abs(xdft)/N).*2).^2;

when computing voxel-wise ALFF

Is anything wrong or I misunderstood the codes?

Q2: I'm a little puzzled about why it's multiplied by two here from 2:end-1

        psdx(2:end-1) = 2*psdx(2:end-1);

Looking forward to your reply. Thank you so much.

Best regards,
CW

**Comment by Enigma-C137** [comment]
Sorry if there are grammatical mistakes, I'm not a native English speaker.

**Comment by abhogal-lab** [comment]
Hey Enigma,

regarding the first question, I believe the answer lies in the paper by Yang et al (https://doi.org/10.1016/j.neuroimage.2007.01.054):

'the time series were transformed to frequency domain using fast Fourier transform (FFT) (parameters: taper percent = 0, FFT length = shortest) and the power spectrum was obtained. Since the power of a given frequency is proportional to the square of the amplitude of this frequency component in the original time series in time domain, the power spectrum obtained by FFT was square rooted and then averaged across 0.01–0.08 Hz at each voxel. This averaged square root was taken as the ALFF'

some Matlab code I found online:

https://nl.mathworks.com/help/matlab/math/basic-spectral-analysis.html

power = abs(y).^2/n;    % power of the DFT

!so here there already seems to be an error in my code in that my division by N is in the wrong place - thanks for that!

I've updated the code now based on your comment.

Regarding the multiplication by 2 - I believe this is something I picked up along the way to understanding how to work with the power spectrum. It has to do with the fact that the you can calculate both the double sided and single sided spectrum:

https://nl.mathworks.com/help/matlab/ref/fft.html

But now that you've got me thinking again, I don't know why/if this is more correct for ALFF. So I will look into it this week and come back to you!


Thanks for taking a critical look at my code - ALFF is something that I have not spent enough time on so there can always be errors/typos!

Let me know if I can help with other questions

Best,
Alex

**Comment by Enigma-C137** [comment]
Thanks for your answer, I've learned a lot. :)
