### ISSUE TITLE
lagCVR() index error

### ISSUE THREAD

**Issue by dariusvalevicius** [abhogal-lab/seeVR#13]
Hello,

I'm encountering an index error in lagCVR() on line 176. The error is paired with an odd comment on that line, suggesting that there is a known problem, but the comment is from the initial commit 2 years ago.

The error log:

> Creating optimized regressor
Correlating TS voxelwise to probe 1
 . 
 . 
 . 
Index in position 1 exceeds array bounds.

> Error in lagCVR (line 176)
            [~,lags] = xcorr(newprobe,gm_voxel_ts_nonan(1,:),'coeff');  %%%%%% !!!!!!!!!!

The 'probe' input to lagCVR() is a 350x1 double, if that helps.

Best,
Darius

**Comment by dariusvalevicius** [comment]
This is using seeVR version 1.55 and MATLAB 2021b.

**Comment by abhogal-lab** [comment]
Hi Darius,

Thanks for trying out my tools and letting me know about the potential bug. I think that comment is just an old artifact since this line is really only there to setup the vector containing the potential lag indices. I can't seem to reproduce the error using my data so I suspect it might have something to do with the function inputs.

Can you please try some things to help me figure out what might be the problem and/or help me to reproduce the error?:

1) please provide the function call with the sizes of the inputs (i.e. func data, masks etc.)
2) place a break point at line 176 and run the function to see what the size of the newprobe and gm_voxel_ts_nonan is?
3) download tutorial Demo #1 from www.seeVR.nl and see if that successfully runs? If yes, confirm that your inputs are matching those used in the tutorial.

Otherwise I'm happy to do a call to help figure out the problem using your data directly (a.bhogal@umcutrecht.nl).

Best,
Alex

**Comment by dariusvalevicius** [comment]
Hi Alex, thanks so much for the prompt response!

Using breakpoints to test the inputs to xcorr, I seem to have isolated the problem. For some reason, the "cast" function (called inside of grabTimeseries()) in my MATLAB installation contains no code, only comments, and returns empty arrays, causing the gm_voxel_tx input(1,:) to throw an index error.

![image](https://github.com/abhogal-lab/seeVR/assets/80284641/e1d0534d-373d-4746-a7eb-76d4d7af5ac3)

I guess I'll try a reinstall of MATLAB - super strange!

Best,
Darius

**Comment by abhogal-lab** [comment]
Thanks Darius,

Sounds like a bug to me! I'll be sure to implement some more checks.
